### ISSUE TITLE
Mac tcl-tk version issue

### ISSUE THREAD

**Issue by riotdream** [tmb5cg/Fifa-Autobidder#38]
I've got an error with tcl-tk, I've installed 3.6 with brew but and added those 3 lines to zehra

echo 'export PATH="/usr/local/opt/tcl-tk/bin:$PATH"' >> ~/.zshrc
echo 'export LDFLAGS="-L/usr/local/opt/tcl-tk/lib"' >> ~/.zshrc
echo 'export CPPFLAGS="-I/usr/local/opt/tcl-tk/include"' >> ~/.zshrc

but is a no go

```
suzughia@MacBook Pro 13 Retina Fifa-Autobidder % make run
python3 src/run.py
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "/Users/suzughia/Fifa-Autobidder/src/run.py", line 13, in <module>
    root.tk.call("source", "azure.tcl")
_tkinter.TclError: version conflict for package "Tk": have 8.5.9, need 8.6
make: *** [run] Error 1

```

**Comment by yannmazita** [comment]
The app expects version 8.6 of Tk to be installed. Your system-provided Tk is on version 8.5.9.

**Comment by prebollar15** [comment]
@riotdream I was running into the same issues as you but was able to solve them by following these steps: https://stackoverflow.com/questions/60469202/unable-to-install-tkinter-with-pyenv-pythons-on-macos

**Comment by tmb5cg** [comment]
Maybe I need to update the requirements.txt? I'm not having this issue unfortunately
