### ISSUE TITLE
use_undetected_chromedriver seems inverted

### ISSUE THREAD

**Issue by stepanovep** [tmb5cg/Fifa-Autobidder#39]
https://github.com/tmb5cg/Fifa-Autobidder/blob/8db564f7cf2f6ea24715b19eac8e9f91fbc0861b/src/helpers.py#L101

Hi there!
I am a bit confused with flag `use_undetected_chromedriver`.
It seems like in order to be more undetectable we should use what's inside `else` branch,
but it does the opposite.

**Comment by tmb5cg** [comment]
I can't remember specifics, but I think there were issues fetching UC and I made a quick edit to the codebase but you are probably right!
