### ISSUE TITLE
Problems fetching FutBin Prices

### ISSUE THREAD

**Issue by Domtaholic** [tmb5cg/Fifa-Autobidder#42]
Im running in a lot of problems lately, as of today can´t fetch futbin prices. Heres the stacktrace:
![image](https://user-images.githubusercontent.com/3584433/205622299-e780184a-52b6-46ca-839c-ecb3cefbb0c1.png)

System: Windows
Chrome: Newest version / ChromeDriver: newest Version
Autobidder: latest Version

Does it still work for you guys?
And btw. thx for that awesome tool, really appreciate the time and effort you put into this <3

**Comment by dacdam** [comment]
Same error and same configuration.
I changed timeout from 10 to 50 but does not fix.

**Comment by tmb5cg** [comment]
Fixed! Lmk if issues
