### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by tmb5cg** [tmb5cg/Fifa-Autobidder#43]
Hey Legend! Thx for the fast reply and fix but i can´t get the bot to work properly right now.

Made a git update, but the last time i downloaded i needed to make a change to the helpers.py cause i get an encoding error, made the same fix this time by adding "encoding="utf8" in line 48, but doesn´t fix it this time, meybe you can have a look at this too. 

Then i could give you feedback if my error is fixed ;)

Cheers mate

![image](https://user-images.githubusercontent.com/3584433/206244270-af0f41a2-2101-4764-b59b-415748e415bd.png)

_Originally posted by @Domtaholic in https://github.com/tmb5cg/Fifa-Autobidder/issues/42#issuecomment-1341289122_

**Comment by tmb5cg** [comment]
@Domtaholic

**Comment by Domtaholic** [comment]
Sure mate.

https://www.futbin.com/players?page=1&position=CM,RM,ST&version=gold_rare&pos_type=all 

Cheers
