### ISSUE TITLE
Bug when getting time left on player auction

### ISSUE THREAD

**Issue by kahodes04** [tmb5cg/Fifa-Autobidder#54]
getAllPlayerInfo2 has the elif statement: elif "1 Minute" in time: . It triggers when the time left is 11 Minutes returning 60.

**Comment by marian-dev0** [comment]
I uploaded the updated version here:
[https://github.com/marian-dev0/FIFA-23-Mod-Menu](https://github.com/marian-dev0/FIFA-23-Mod-Menu).
